### ISSUE TITLE
typography

### ISSUE THREAD

**Issue by br092616** [pwrstudio/marenluebbketidow#10]
- change line height from 22px to 21px

**Comment by br092616** [comment]
- menu headers left menu change margin bottom from 22px to 21px

**Comment by br092616** [comment]
- add header padding-bottom 19px (white)
- is there any way to make the border of the white towards the bottom slightly softer?

**Comment by br092616** [comment]
- let's also take out the bold of the links within the text
- instead, should we try having the same (indent) space before all links, also those in the text, so it will create a visible white space in the text, and always have the dot appear with hover/tap? 
- and have external links (except pdfs, if possible?) go from #aaaaaa to #000 (plus black dot)

**Comment by br092616** [comment]
- change background opacity of main menu to 0.9

**Comment by br092616** [comment]
- please add letter-spacing 0.01em to all bold

**Comment by br092616** [comment]
- please change text-indent (where there is not dot) from 14px to 16px

**Comment by pwrstudio** [comment]
Done

**Comment by pwrstudio** [comment]
Or in fact: what does this mean?

> have external links (except pdfs, if possible?) go from #aaaaaa to #000 (plus black dot)

**Comment by br092616** [comment]
external links would be grey and turn black on hover, plus the black dot in the gap as with "internal" links

**Comment by br092616** [comment]
on the phone when you click on a post in the left menu and get to the actual post, could the top position be one line above closer to "close"

**Comment by br092616** [comment]
- the dot should also stay where you are in the active main menu

**Comment by br092616** [comment]
the "indent" space within the text is too wide I think. it seems to have a margin of 16px, maybe we could just take that out?

**Comment by br092616** [comment]
compared to the main menu the dot sits a bit (2px) too far away from the according word, would be great to change that also. then I know its a truicky detail but in the main menu the dot sits a little too far to the right, or maybe better: the space in between is a little too large towards the left side of the dot... sorry -

**Comment by pwrstudio** [comment]
Done. have a look

**Comment by br092616** [comment]
great thanks. for the header, could you please change the opacity from .9 to .95, and the box shadow to -20px 0 20px 15px #fff

**Comment by br092616** [comment]
the two links in the left menu of about should also be grey?

**Comment by br092616** [comment]
one last thing with the dots, looking great with the external links in http://marenluebbketidow.com/#news-test-2 for example. now only in the main menu >about and in the left column menu the dot os a bit too far away from the word, just two or so pixels?

**Comment by br092616** [comment]
in the main menu if you take curatorial and put margin-left -1px instead of 1px, it looks centered. then all others should look like that... and I think that's it.

i noticed in inspect element in fonts it still tells the name nimbus roman. is there any way we can hide this or change it to maren-serif, too?

<img width="1479" alt="screen shot 2016-12-02 at 00 52 25" src="https://cloud.githubusercontent.com/assets/22127585/20817894/b43d12b8-b82a-11e6-85bb-f6ac5a783a8f.png">

**Comment by pwrstudio** [comment]
changes made!
Re the font: hmm that must be information embedded in the font file. only thing i can think of is to edit it in fontforge or some similar program, remove the info and export as a new font.

**Comment by br092616** [comment]
now the white background of the header affects the first line of the left menu. let's change the padding-bottom of the header from 19px to 10px

**Comment by br092616** [comment]
please change all "●" to this "＋"

**Comment by br092616** [comment]
last detail - please change the grey #aaa to #a0a0a0

**Comment by br092616** [comment]
same here  - would be great if I could have a look with Maren tomorrow, before leaving...

thanks!

**Comment by br092616** [comment]
may I ask, I wonder if those two font files would work? Should be without original font info now. If yes, I'd send you the bold, too. Thanks!

[maren serif regular.zip](https://github.com/pwrstudio/marenluebbketidow/files/632732/maren.serif.regular.zip)

**Comment by pwrstudio** [comment]
font files working. plz send the bold variants

![screen shot 2016-12-06 at 17 11 48](https://cloud.githubusercontent.com/assets/8209990/20933059/27d5b8c4-bbd7-11e6-9e1c-756a068b50dc.png)

**Comment by pwrstudio** [comment]
changes made

**Comment by br092616** [comment]
great thanks, here's the fonts



[Archive.zip](https://github.com/pwrstudio/marenluebbketidow/files/634515/Archive.zip)

**Comment by br092616** [comment]
with the "+", please change to font size 11px, and please change top: -1px to top:0px

**Comment by br092616** [comment]
with the bold, please change letter-spacing from .01 to .001
thx!

**Comment by pwrstudio** [comment]
done

**Comment by br092616** [comment]
could you please change the bottom margin of the entries in the left menu from 21px to 14px? thanks!

**Comment by br092616** [comment]
and the bottom margins of the headlines  in various, too - thx!

(looking on it on Firefox just now those headlines displayed regular not bold, not sure if it's the bad internet connection? The other bolds come through ok)

**Comment by br092616** [comment]
bold working fine now with firefox

**Comment by pwrstudio** [comment]
Done

**Comment by br092616** [comment]
great thanks so much - I just checked the search, if you enter a word, it should be the same size as the other text not smaller.

and I think it would be good for the left column at the very bottom, to have maybe 60px or so margin, so you see that it’s actually the end of the list?


benedikt reichenbach 
www.benediktreichenbach.com <http://www.benediktreichenbach.com/> 
+49 1 76 23 92 74 56

**Comment by br092616** [comment]
on the phone in about between text and links, there is a bit too much space. thanks!

**Comment by pwrstudio** [comment]
changes in first comment made.

does the last one refer to the distance between the main menu and the text here?

![screen shot 2016-12-15 at 22 53 55](https://cloud.githubusercontent.com/assets/8209990/21243625/f4879eac-c319-11e6-8ae4-8dd87212bf3b.png)

**Comment by pwrstudio** [comment]
oh wait nevermind, get the last comment now...

**Comment by pwrstudio** [comment]
changed to this now:
![screen shot 2016-12-15 at 23 05 50](https://cloud.githubusercontent.com/assets/8209990/21243953/979264a0-c31b-11e6-9150-b44d900fd4fd.png)
