### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by br092616** [pwrstudio/marenluebbketidow#11]
- main menu cut off on the left now on my iphone. how about putting everything a tiny bit smaller, also the margins a o it fits in vertical layout?

- probably better to simply drop the search function on the phone

- the zooming is a bit confusing now. let's just take it out?

- too much space between about text and links etc

**Comment by br092616** [comment]
- can the close button sit on the same height as the logo, with the same white transparent background?

**Comment by br092616** [comment]
I think the margins are good actually, could we try simply with slightly smaller type size?

**Comment by br092616** [comment]
when clicking a post in the left menu, could there be a short transition effect, could the dot just appear briefly where it does on the large screen, before you get to the post?

**Comment by br092616** [comment]
the zooming is not working well now, easiest to take it out?

**Comment by br092616** [comment]
on the phone the only thing is when reading the close button and white bar are too present in relation to the text - could you reduce the top margin for both, by not-quite one line?

oh and how about the zooming, could we take that out?

**Comment by pwrstudio** [comment]
reduced the top margin by half a line-height.

re: zoom: i have disabled it, if this is on an iphone it is due to this:
http://stackoverflow.com/a/37859168

**Comment by br092616** [comment]
ok thanks!

please move the "close" up a little more, and then also the actual text - i think it will be nice once its closer to where the main menu is, maybe just one line below? 

With the effect of the white background of the main menu, and close, I understand it’s tricky also in terms of the margins - I wonder how it would be if the bottom-border would be smoother, less of a line, and have the effect spread less?

hope it makes sense, let me know. In the browser it all looks all god as is now.

**Comment by pwrstudio** [comment]
changes made now. reduced the space in the close-header with half a line above and half a line below. and moved the main text up one line.
