### ISSUE TITLE
Movement of type on hover when switching from regular weight to bold

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/marenluebbketidow#2]

**Comment by br092616** [comment]
can we add a letter spacing to the bold? I did that in the design, it might work? In general with typography, maybe easiest if I edit the css directly? can I do this from github?

**Comment by br092616** [comment]
I'm thinking instead of trying to get the regular-bold transition right, we might drop the bold and work with a hover state as on www.tonk.ch, for the main menu and all links also in addition to the black dot in the sub menu.

**Comment by br092616** [comment]
with the same margins as on www.tonk.ch, all black...

**Comment by br092616** [comment]
only the main menu should be bold from the beginning, I think that would make sense.

and then the bold style in general should have letter-spacing 0.01em

**Comment by br092616** [comment]
ah I'm sorry, not so sure about the tonk hover state thinking about it more. it will be a problem with the main menu for sure.

**Comment by br092616** [comment]
I'm pretty sure the main menu should be bold, always.

**Comment by br092616** [comment]
and I think it would be right to have that dot also appear in the menu, the same way it does below: as a hover state and indicating what is active. by the way in about the dots won't display.

**Comment by pwrstudio** [comment]
dot added as hover state to the main menu now. let me know what you think. 

another option is a simple underline on hover/active....

![screen shot 2016-11-24 at 17 05 41](https://cloud.githubusercontent.com/assets/8209990/20604764/65348880-b268-11e6-8674-5328d8a9878f.png)

**Comment by br092616** [comment]
I think it's better. Looking at it I think the main menu should just be regular not bold, with the dot the same as in the left menu. referring to the size and position of the dot as is now in the left menu, let'S try two pixel smaller (12px) and one pixel up towards the center of the line (top:-1) - also let's decrease the indent to 14px. and then have the main menu look identical to all this, also the distance between dot and words.

**Comment by pwrstudio** [comment]
changed now 🎱

**Comment by br092616** [comment]
in the main menu, to each menu item can we add one pixel width, please - except curatorial, let's add two pixel here (ideally I could things like this myself?)

**Comment by pwrstudio** [comment]
done

**Comment by br092616** [comment]
oh it seems the black dot didn't move with it - the idea was it should be in the center of the two, right now it sits a bit towards the left

**Comment by pwrstudio** [comment]
ah okej, so the bullet should be centered in the space between the menu items?

Except for the first one, that should be spaced as the ones in the post menu, right?

![screen shot 2016-11-30 at 11 58 40](https://cloud.githubusercontent.com/assets/8209990/20749887/770c35ea-b6f4-11e6-8418-50e072f783a9.png)

**Comment by br092616** [comment]
yes, thanks

**Comment by pwrstudio** [comment]
Done
