### ISSUE TITLE
Cross-browser testing

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/marenluebbketidow#3]
Currently just checked in Chrome...

**Comment by br092616** [comment]
in Firefox there is a scrollbar. Would be great to have it hidden here as well.

**Comment by pwrstudio** [comment]
Scrollbar hidden on firefox too now (not updated on server yet though)

**Comment by br092616** [comment]
in safari the left menu seems a little bumpy when moving over it

**Comment by pwrstudio** [comment]
fixed now in safari
