### ISSUE TITLE
title of the site

### ISSUE THREAD

**Issue by br092616** [pwrstudio/marenluebbketidow#4]
- the dots of the ü seem to be off a little?
- it might have been not clear enought from the draft: the landing page would be a sort of "News" page. Clicking the name would always bring you back to that page

**Comment by pwrstudio** [comment]
Regarding the dots: has to do with the rendering of the font in that case. looks fine here though, although I am not natively familiar with the ü

Regarding landing page: so this should show the most recent posts (say 10 of them?) from all categories (texts, curatorial, editorial, etc...)?

**Comment by br092616** [comment]
can we render it differently, or is there a way to avoid the problem with the rendering? should look like ü - or we write ue for now.

the landing page is x manual posts, a menu just like the others, I think?

**Comment by pwrstudio** [comment]
ah i see it now in firefox. yes looks very weird. looks good in chrome:

![screen shot 2016-11-22 at 22 48 45](https://cloud.githubusercontent.com/assets/8209990/20543465/330efeca-b106-11e6-88dd-e2053357c454.png)

will see if there is some fix, but the details of the text rendering are general outside of control.

RE: landing page: okej so it is a special category of posts that are only shown on that page? not an aggregate of the other categories?

**Comment by br092616** [comment]
ok - yes exactly for the landing page.

sorry to be asking again - I got the video to work in the logo - but is there a way to play a video in the background, instead of an image?

benedikt reichenbach 
www.benediktreichenbach.com 
+49 1 76 23 92 74 56

**Comment by br092616** [comment]
for Irina’s logo box in safari there are two horizontal lines… wondering if there would be some other way than having a border, would it be different with margins…?

**Comment by pwrstudio** [comment]
News/landing page added....
