### ISSUE TITLE
Font rendering (ü) on firefox

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/marenluebbketidow#5]
![screen shot 2016-11-22 at 22 49 48](https://cloud.githubusercontent.com/assets/8209990/20545210/32a815fe-b10e-11e6-9b16-e07172f6b336.png)

**Comment by pwrstudio** [comment]
hmm yes seems to be some osrt of incompatibility between the font-file and firefox. changing to 'ue' is the only solution i can think of.

**Comment by br092616** [comment]
let's try ue

**Comment by pwrstudio** [comment]
done

**Comment by br092616** [comment]
sorry Maren says she would prefer to have the real ü. Anything we could do about the font rendering? a simple times ü maybe?

**Comment by pwrstudio** [comment]
it is a problem with the font-file. same for all characters with diacritic marks, in firefox:

![screen shot 2016-11-25 at 13 05 01](https://cloud.githubusercontent.com/assets/8209990/20624934/239f00be-b310-11e6-86f1-27b70e7c2d54.png)
![screen shot 2016-11-25 at 13 05 06](https://cloud.githubusercontent.com/assets/8209990/20624935/23a098a2-b310-11e6-99fc-7e187861d4fa.png)
![screen shot 2016-11-25 at 13 05 11](https://cloud.githubusercontent.com/assets/8209990/20624936/23a32a54-b310-11e6-8d4c-01122277e7b2.png)

I would say either find another font-file of the typeface, or switch to over to some similar type (plain times new roman perhaps)

**Comment by br092616** [comment]
oh -

I found another set, should be identical but maybe it works with this one?

to be sure, it's the same typeface as on reading resources. if they ever use ä's or ö's or ü's.

[Untitled.zip](https://github.com/pwrstudio/marenluebbketidow/files/613202/Untitled.zip)

**Comment by br092616** [comment]
just checked on reading resources and firefox, umlaute working all well there

**Comment by pwrstudio** [comment]
hmm yeah umlaut seems to be working fine on firefox on marens site too now!

![screen shot 2016-11-30 at 14 54 21](https://cloud.githubusercontent.com/assets/8209990/20754807/f3b849cc-b70c-11e6-9f4d-2c52001c4463.png)

do you see the same?

**Comment by pwrstudio** [comment]
Are you also seeing the ü correctly on firefox?

**Comment by br092616** [comment]
yes!


benedikt reichenbach 
www.benediktreichenbach.com 
+49 1 76 23 92 74 56

**Comment by pwrstudio** [comment]
magic
