### ISSUE TITLE
wordpress outer post structure

### ISSUE THREAD

**Issue by br092616** [pwrstudio/marenluebbketidow#9]
- add drag and drop option/change post position function to list of posts

- newest news should always be displayed on top, if possible

**Comment by br092616** [comment]
- I think the title displayed in the list of posts should be the title from the left menu. if you look at http://marenluebbketidow.com/texts#%e2%80%89headline-hier, the post won't display. I think I changed the headline after publishing...

**Comment by br092616** [comment]
- please add function add/edit users here, too - I mean generally, in the settings

**Comment by pwrstudio** [comment]
- drag and drop post order enabled
- User-menu added to settings
- The newest post in news is in fact shown on top. drag and drop changing of the order is enabled for this category as well, but if you dont changint manual it will be chronological.
